# Generated by Django 4.2.2 on 2023-07-08 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bottles', '0002_remove_collector_latitude_remove_collector_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderds', to='bottles.collector'),
        ),
    ]
